#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RescueMaze_ScoreCalculator_Android.Resource", IsApplication=true)]

namespace RescueMaze_ScoreCalculator_Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int button1 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int button10 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int button11 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int button12 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int button13 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int button14 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int button15 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int button2 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int button3 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int button4 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int button5 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int button6 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int button7 = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int button8 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int button9 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int checkBox4 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int checkBox5 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int checkBox6 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int checkBox7 = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int editNumber1 = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int editText1 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int itemAbout = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int itemExit = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int itemReset = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int itemSave = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int linearLayout1 = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int linearLayout10 = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int linearLayout11 = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int linearLayout12 = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int linearLayout2 = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int linearLayout3 = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int linearLayout4 = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int linearLayout5 = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int linearLayout6 = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int linearLayout7 = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int linearLayout9 = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int textView1 = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int textView2 = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int textView3 = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int textView4 = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int textView5 = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int textView6 = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int textView8 = 2130837546;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int User_Input_Dialog_Box_RoundNumber = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int User_Input_Dialog_Box_TeamName = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F040000
			public const int action_menu = 2130968576;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
